let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const listDiscountCtrl = require('../../controllers/festumevento/discounts/list');
const saveDiscountCtrl = require('../../controllers/festumevento/discounts/save');
const onoffDiscountCtrl = require('../../controllers/festumevento/discounts/onoff');
const getoneDiscountCtrl = require('../../controllers/festumevento/discounts/getone');
router.get('/', helper.authenticateToken, listDiscountCtrl.withoutpagination);
router.post('/', helper.authenticateToken, listDiscountCtrl.withpagination);
router.post('/save', helper.authenticateToken, saveDiscountCtrl.savediscount);
router.post('/onoff', helper.authenticateToken, onoffDiscountCtrl.onoffdiscount);
router.post('/getone', helper.authenticateToken, getoneDiscountCtrl.getonediscount);
module.exports = router;