let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const listEventBookingCouponsCtrl = require('../../controllers/festumevento/eventcoupons/list');
const saveEventBookingCouponsCtrl = require('../../controllers/festumevento/eventcoupons/save');
const onoffEventBookingCouponsCtrl = require('../../controllers/festumevento/eventcoupons/onoff');
const getoneEventBookingCouponsCtrl = require('../../controllers/festumevento/eventcoupons/getone');
router.post('/', helper.authenticateToken, listEventBookingCouponsCtrl.withpagination);
router.get('/', helper.authenticateToken, listEventBookingCouponsCtrl.withoutpagination);
router.post('/save', helper.authenticateToken, saveEventBookingCouponsCtrl.saveeventcoupon);
router.post('/onoff', helper.authenticateToken, onoffEventBookingCouponsCtrl.onoffeventcoupon);
router.post('/getone', helper.authenticateToken, getoneEventBookingCouponsCtrl.getoneeventcoupon);
module.exports = router;
