let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const listEventCtrl = require('../../controllers/festumevento/events/list');
const approvedisapproveEventCtrl = require('../../controllers/festumevento/events/approvedisapprove');
const getoneEventCtrl = require('../../controllers/festumevento/events/getone');
router.post('/', helper.authenticateToken, listEventCtrl.withpagination);
router.post('/approvedisapprove', helper.authenticateToken, approvedisapproveEventCtrl.approvdisapproveevent);
router.post('/getone', helper.authenticateToken, getoneEventCtrl.getoneevent);
module.exports = router;