let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const listEventCtrl = require('../../controllers/festumevento/events/list');
const approvedisapproveEventCtrl = require('../../controllers/festumevento/events/approvedisapprove');
const getoneEventCtrl = require('../../controllers/festumevento/events/getone');
const listEventAttendeesCtrl = require('../../controllers/festumevento/events/attendeeslist');
const eventBookedSummeryCtrl = require('../../controllers/festumevento/events/bookedsummery');
const exportAttendeesCtrl = require('../../controllers/festumevento/events/exportattendees');
router.post('/', helper.authenticateToken, listEventCtrl.withpagination);
router.post('/approvedisapprove', helper.authenticateToken, approvedisapproveEventCtrl.approvdisapproveevent);
router.post('/getone', helper.authenticateToken, getoneEventCtrl.getoneevent);
router.post('/attendees', helper.authenticateToken, listEventAttendeesCtrl.withpagination);
router.post('/bookedsummery', helper.authenticateToken, eventBookedSummeryCtrl.withoutpagination);
router.post('/exportattendees', helper.authenticateToken, exportAttendeesCtrl.exportattendees);
module.exports = router;