let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const listEventCategoryCtrl = require('../../controllers/festumevento/eventcategories/list');
const saveEventCategoryCtrl = require('../../controllers/festumevento/eventcategories/save');
const onoffEventCategoryCtrl = require('../../controllers/festumevento/eventcategories/onoff');
const getoneEventCategoryCtrl = require('../../controllers/festumevento/eventcategories/getone');
router.post('/', helper.authenticateToken, listEventCategoryCtrl.withpagination);
router.post('/list', helper.authenticateToken, listEventCategoryCtrl.withoutpagination);
router.post('/save', helper.authenticateToken, saveEventCategoryCtrl.saveeventcategory);
router.post('/onoff', helper.authenticateToken, onoffEventCategoryCtrl.onoffeventcategory);
router.post('/getone', helper.authenticateToken, getoneEventCategoryCtrl.getoneeventcategory);
module.exports = router;
