let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const fileHelper = require('../../utilities/multer.functions');
const fCoinBalanceCtrl = require('../../controllers/festumevento/fcoins/balance');
const fCoinGenerateCtrl = require('../../controllers/festumevento/fcoins/generate');
const fCoinInTransactionCtrl = require('../../controllers/festumevento/fcoins/in');
const fCoinOutTransactionCtrl = require('../../controllers/festumevento/fcoins/out');
router.post('/coinsin', helper.authenticateToken, fCoinInTransactionCtrl.fcoinintransactions);
router.post('/coinsout', helper.authenticateToken, fCoinOutTransactionCtrl.fcoinouttransactions);
router.post('/generatecoins', helper.authenticateToken, fileHelper.memoryUpload.single('file'), fCoinGenerateCtrl.generatefcoinbalance);
router.get('/coinbalance', helper.authenticateToken, fCoinBalanceCtrl.fcoinbalance);
module.exports = router;