let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const multerFn = require('../../utilities/multer.functions');
const listItemCtrl = require('../../controllers/festumevento/items/list');
const onoffItemCtrl = require('../../controllers/festumevento/items/onoff');
const getoneItemCtrl = require('../../controllers/festumevento/items/getone');
const saveItemCtrl = require('../../controllers/festumevento/items/save');
router.get('/', helper.authenticateToken, listItemCtrl.withoutpagination);
router.post('/', helper.authenticateToken, listItemCtrl.withpagination);
router.post('/onoff', helper.authenticateToken, onoffItemCtrl.onoffitem);
router.post('/getone', helper.authenticateToken, getoneItemCtrl.getoneitem);
router.post('/save', helper.authenticateToken, multerFn.memoryUpload.single("file"), saveItemCtrl.saveitem);
module.exports = router;
