var express = require('express');
var router = express.Router();
const helper = require('../../utilities/helper');
const listOnlineOfferCtrl = require('../../controllers/festumevento/onlineoffers/list');
const getoneOnlineOfferCtrl = require('../../controllers/festumevento/onlineoffers/getone');
const approvedisapproveOnlineOfferCtrl = require('../../controllers/festumevento/onlineoffers/approvedisapprove');
router.post('/', helper.authenticateToken, listOnlineOfferCtrl.withpagination);
router.post('/getone', helper.authenticateToken, getoneOnlineOfferCtrl.getoneonlineoffer);
router.post('/approvedisapprove', helper.authenticateToken, approvedisapproveOnlineOfferCtrl.approvedisapproveonlineoffer);
module.exports = router;