let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const saveDepositeForOragnizerCtrl = require('../../controllers/festumevento/organizers/savedeposite');
const returnDepositeForOragnizerCtrl = require('../../controllers/festumevento/organizers/returndeposite');
const listOragnizerCtrl = require('../../controllers/festumevento/organizers/list');
const approvedisapproveOragnizerCtrl = require('../../controllers/festumevento/organizers/approvedisapprove');
const getoneOragnizerCtrl = require('../../controllers/festumevento/organizers/getone');
const exportOragnizerCtrl = require('../../controllers/festumevento/organizers/export');
router.post('/savedeposite', helper.authenticateToken, saveDepositeForOragnizerCtrl.saveorganizerdeposite);
router.post('/returndeposite', helper.authenticateToken, returnDepositeForOragnizerCtrl.returnorganizerdeposite);
router.post('/', helper.authenticateToken, listOragnizerCtrl.withpagination);
router.get('/', helper.authenticateToken, listOragnizerCtrl.withoutpagination);
router.post('/approvedisapprove', helper.authenticateToken, approvedisapproveOragnizerCtrl.approvedisapproveorganizer);
router.post('/getone', helper.authenticateToken, getoneOragnizerCtrl.getoneorganizer);
router.post('/export', helper.authenticateToken, exportOragnizerCtrl.exportorganizer);
module.exports = router;