let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const fileHelper = require('../../utilities/multer.functions');
const listPlatformCtrl = require('../../controllers/festumevento/platforms/list');
const savePlatformCtrl = require('../../controllers/festumevento/platforms/save');
const getonePlatformCtrl = require('../../controllers/festumevento/platforms/getone');
const onoffPlatformCtrl = require('../../controllers/festumevento/platforms/onoff');
router.get('/', helper.authenticateToken, listPlatformCtrl.withoutpagination);
router.post('/', helper.authenticateToken, listPlatformCtrl.withpagination);
router.post('/save', helper.authenticateToken, fileHelper.memoryUpload.single('file'), savePlatformCtrl.saveplatform);
router.post('/getone', helper.authenticateToken, getonePlatformCtrl.getoneplatform);
router.post('/onoff', helper.authenticateToken, onoffPlatformCtrl.onoffplatform);
module.exports = router;
