var express = require('express');
var router = express.Router();
const helper = require('../../utilities/helper');
const listShopOfferCtrl = require('../../controllers/superadmin/shopoffer/list');
const getoneShopOfferCtrl = require('../../controllers/superadmin/shopoffer/getone');
const approveShopOfferCtrl = require('../../controllers/superadmin/shopoffer/approve');
const rejectShopOfferCtrl = require('../../controllers/superadmin/shopoffer/reject');
const deleteShopOfferCtrl = require('../../controllers/superadmin/shopoffer/remove');
const offerAttendeesCtrl = require('../../controllers/superadmin/shopoffer/attendees');
router.post('/', helper.authenticateToken, listShopOfferCtrl.list);
router.post('/getone', helper.authenticateToken, getoneShopOfferCtrl.getone);
router.post('/approve', helper.authenticateToken, approveShopOfferCtrl.approve);
router.post('/reject', helper.authenticateToken, rejectShopOfferCtrl.reject);
router.post('/remove', helper.authenticateToken, deleteShopOfferCtrl.remove);
router.post('/attendees', helper.authenticateToken, offerAttendeesCtrl.attendees);
router.post('/exportattendees', helper.authenticateToken, offerAttendeesCtrl.exportattendees);
module.exports = router;