let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const listShopCategoryCtrl = require('../../controllers/festumevento/shopcategories/list');
const saveShopCategoryCtrl = require('../../controllers/festumevento/shopcategories/save');
const getoneShopCategoryCtrl = require('../../controllers/festumevento/shopcategories/getone');
const onoffShopCategoryCtrl = require('../../controllers/festumevento/shopcategories/onoff');
router.post('/', helper.authenticateToken, listShopCategoryCtrl.withpagination);
router.get('/', helper.authenticateToken, listShopCategoryCtrl.withoutpagination);
router.post('/save', helper.authenticateToken, saveShopCategoryCtrl.saveshopcategory);
router.post('/getone', helper.authenticateToken, getoneShopCategoryCtrl.getoneshopcategory);
router.post('/onoff', helper.authenticateToken, onoffShopCategoryCtrl.onoffshopcategory);
module.exports = router;
