var express = require('express');
var router = express.Router();
const helper = require('../../utilities/helper');
const listShopCtrl = require('../../controllers/superadmin/shops/list');
const getoneShopCtrl = require('../../controllers/superadmin/shops/getone');
const approveShopCtrl = require('../../controllers/superadmin/shops/approve');
const rejectShopCtrl = require('../../controllers/superadmin/shops/reject');
const deleteShopCtrl = require('../../controllers/superadmin/shops/remove');
router.post('/', helper.authenticateToken, listShopCtrl.list);
router.post('/getone', helper.authenticateToken, getoneShopCtrl.getone);
router.post('/approve', helper.authenticateToken, approveShopCtrl.approve);
router.post('/reject', helper.authenticateToken, rejectShopCtrl.reject);
router.post('/remove', helper.authenticateToken, deleteShopCtrl.remove);
module.exports = router;