let constants = {
    DEFAULT_DB: 'superadmin',
    FESTUMEVENTO_DB: 'festumevento',
    EVENTOPACKAGE_DB: 'eventopackage',
    FESTUMCOIN_DB : 'festumcoin',
    FESTUMFIELD_DB : 'festumfield',
    FESTUMADVERTISINGMEDIA_DB : 'festumadvertisingmedia',
    MODELS : {
        admins: 'admins',
        roles: 'roles',
        projects : 'projects'
    },
    FE_MODELS : {
        admins: 'admins',
        executives: 'executives',
        subadmins: 'subadmins',
        superadmins: 'superadmins',
        organizers: 'organizers',
        users: 'users',
        events: 'events',
        eventreviews: 'eventreviews',
        offers: 'offers',
        items: 'items',
        eventcategories: 'eventcategories',
        shopcategories: 'shopcategories',
        discounts: 'discounts',
        shops: 'shops',
        onlineoffers: 'onlineoffers',
        offlineoffers: 'offlineoffers',
        notifications: 'notifications',
        promotionplans: 'promotionplans',
        customerimports: 'customerimports',
        settings: 'settings',
        notificationcoupons: 'notificationcoupons',
        platforms: 'platforms',
        livestreams : 'livestreams',
        livestreamreviews : 'livestreamreviews',
        livestreamwishlists : 'livestreamwishlists',
        subscriptions : 'subscriptions',
        eventwishlists : 'eventwishlists',
        shopreviews : 'shopreviews',
        offlineofferwishlists : 'offlineofferwishlists',
        onlineofferreviews : 'onlineofferreviews',
        onlineofferwishlists : 'onlineofferwishlists',
        eventbookingcoupons : 'eventbookingcoupons',
        getintouches : 'getintouches',
        eventbookings : 'eventbookings',
        entertainmentcomments : 'entertainmentcomments',
        offlineofferbookings : 'offlineofferbookings',
        onlineofferviews : 'onlineofferviews',
        fcointransactions : 'fcointransactions',
        links : 'links',
        offerclicks : 'offerclicks',
        agents : 'agents',
        livestreambookings : 'livestreambookings',
        fcoinintransactions : 'fcoinintransactions',
        fcoins : 'fcoins',
        promotionexistingusers : 'promotionexistingusers',
        livestreamviews : 'livestreamviews',
        shopwishlists : 'shopwishlists',
        organisernotifications : 'organisernotifications',
        organiserchatnotifications : 'organiserchatnotifications',
        usernotifications : 'usernotifications',
        userchatnotifications : 'userchatnotifications',
        uochats : 'uochats',
        emailtemplates : 'emailtemplates',
        smstemplates : 'smstemplates'
    },
    EP_MODELS : {
        admins: 'admins',
        executives: 'executives',
        subadmins: 'subadmins',
        superadmins: 'superadmins',
        organizers: 'organizers',
        users: 'users',
        events: 'events',
        eventreviews: 'eventreviews',
        eventwishlists: 'eventwishlists',
        services: 'services',
        items: 'items',
        equipments: 'equipments',
        categories: 'categories',
        discounts : 'discounts',
        ourproduct : 'ourproduct',
        notifications : 'notifications',
        promotionplans : 'promotionplans',
        customerimports : 'customerimports',
        settings : 'settings',
        notificationcoupons : 'notificationcoupons',
        eventbookingcoupons: 'eventbookingcoupons',
        eventbookings: 'eventbookings',
        getintouches : 'getintouches',
        entertainmentcomments : 'entertainmentcomments',
        fcointransactions : 'fcointransactions',
        fcoinintransactions: 'fcoinintransactions',
        agents : 'agents',
        fcoins : 'fcoins',
        promotionexistingusers : 'promotionexistingusers'
    },
    FC_MODELS : {},
    FF_MODELS : {},
    FAM_MODELS : {}
};
module.exports = constants;
