let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const listAdminCtrl = require('../../controllers/superadmin/admins/list');
const saveAdminCtrl = require('../../controllers/superadmin/admins/save');
const onoffAdminCtrl = require('../../controllers/superadmin/admins/onoff');
const getoneAdminCtrl = require('../../controllers/superadmin/admins/getone');
router.post('/', helper.authenticateToken, listAdminCtrl.listwithpagination);
router.post('/save', helper.authenticateToken, saveAdminCtrl.saveadmin);
router.post('/onoff', helper.authenticateToken, onoffAdminCtrl.activeinactiveadmin);
router.post('/getone', helper.authenticateToken, getoneAdminCtrl.getoneadmin);
module.exports = router;
