let express = require("express");
let router = express.Router();
const helper = require('../../utilities/helper');
const defaultpermissionCtrl = require('../../controllers/superadmin/roles/defaultpermissions');
const listRolesCtrl = require('../../controllers/superadmin/roles/list');
const saveRolesCtrl = require('../../controllers/superadmin/roles/save');
const onoffRolesCtrl = require('../../controllers/superadmin/roles/onoff');
const getoneRolesCtrl = require('../../controllers/superadmin/roles/getone');
router.get('/defaultpermissions', helper.authenticateToken, defaultpermissionCtrl.getdefaultpermissions);
router.get('/', helper.authenticateToken, listRolesCtrl.withoutpagination);
router.post('/', helper.authenticateToken, listRolesCtrl.withpagination);
router.post('/save', helper.authenticateToken, saveRolesCtrl.saverole);
router.post('/onoff', helper.authenticateToken, onoffRolesCtrl.activeinactiverole);
router.post('/getone', helper.authenticateToken, getoneRolesCtrl.getonerole);
module.exports = router;
